### ISSUE TITLE
Build `asset_showcase` as a DevTools extension

### ISSUE THREAD

**Issue by kenzieschmoll** [chtgupta/flutter-asset-showcase#3]
Have you considered building this tool as a Dart & Flutter DevTools extension? This would allow your users to use the tool directly embedded in their IDE without having to run any extra commands. It would also have the added benefit that your DevTools extension could detect the path to the user's asset folder automatically.

If they have a project open in VS Code, IntelliJ or Android Studio that depends on `asset_showcase`, then your tool would show up as a provided DevTools extension that they can open as part of the existing Dart & Flutter DevTools tooling suite.

Resources:
- https://pub.dev/packages/devtools_extensions
- https://docs.flutter.dev/tools/devtools/extensions

**Comment by chtgupta** [comment]
Hey @kenzieschmoll thanks for the suggestion! Will do some research about DevTools and try to make one.
