### ISSUE TITLE
[Feature Request] highlight unused assets

### ISSUE THREAD

**Issue by Fintasys** [chtgupta/flutter-asset-showcase#4]
Great package, thank you for your work!

Would be nice if it would show if the asset is being used or unused. In bigger projects it's happen often that unused resources remain forgotten etc.

**Comment by chtgupta** [comment]
@Fintasys this was my original intuition for making this package. But the fact that Flutter assets are simply packaged into the APK/AAB without a reference registry (like Android) is scary.

It is a common practice where some asset paths are consumed from an API response and drawn on the UI. This feature can be developed, but with fair limitations. Will try to pick this up in some free time. Thanks for all the support!
